Add sand dunes biome to the deserts
TerraformersMC/Terrestria pull request #104
Opened 2020-02-21 22:42 UTC by NeusFear

Need code review

2020-02-23 00:20 UTC, coderbot16 requested changes
The code overall looks good, but I do think that this biome is (quite literally) a bit rough around the edges. A better approach will likely be needed.

2020-02-23 00:20 UTC, coderbot16 commented on src/main/java/com/terraformersmc/terrestria/init/TerrestriaGeneration.java
> +import static com.terraformersmc.terrestria.init.TerrestriaBiomes.*;
I'd like to set up code style so that this doesn't keep oscillating between contributions from different people. It's fine for now I guess.

2020-02-23 00:20 UTC, coderbot16 commented on src/main/java/com/terraformersmc/terrestria/init/TerrestriaGeneration.java
> +		addBiomeVariant(Biomes.DESERT, DUNES, 0.2, "dunes", config, enabledBiomes);
We should use addContinentalBiome instead, addBiomeVariant should only really be used for special cases in generation (such as jungles and oceans)
```suggestion
		addContinentalBiome(DUNES, OverworldClimate.DRY, 0.2, "dunes", config, enabledBiomes);
```

2020-02-23 00:20 UTC, coderbot16 commented on src/main/java/com/terraformersmc/terrestria/surface/DuneSurfaceBuilder.java
> +		double blend = MathHelper.clamp((vHeight - seaLevel) * 0.125, 0, 1);
```suggestion
		// TODO: Blending doesn't work some of the time
		double blend = MathHelper.clamp((vHeight - seaLevel) * 0.125, 0, 1);
```

2020-02-24 21:33 UTC, NeusFear commented on src/main/java/com/terraformersmc/terrestria/init/TerrestriaGeneration.java
> +import static com.terraformersmc.terrestria.init.TerrestriaBiomes.*;
let me know if you set one up.

2020-03-03 20:30 UTC, merged