Reimplement Outback
TerraformersMC/Terrestria pull request #114
Opened 2020-04-13 19:36 UTC by SuperCoder7979

Reimplement outback with a better surface builder and more sane code.

2020-04-13 19:41 UTC, NeusFear requested changes
Other than these 2 style changes it looks good.

2020-04-13 19:41 UTC, NeusFear commented on src/main/java/com/terraformersmc/terrestria/feature/trees/ShrubFeature.java
> +		if (world.getBlockState(pos.down()) != Blocks.GRASS_BLOCK.getDefaultState()) return false;
This should be on both lines

2020-04-13 19:41 UTC, NeusFear commented on src/main/java/com/terraformersmc/terrestria/feature/trees/ShrubFeature.java
> +		}
This would be better if it were just 2 setblock and a single if statement to eliminate the int instance and using a nextBollean

2020-04-13 19:41 UTC, NeusFear commented on src/main/java/com/terraformersmc/terrestria/feature/trees/ShrubFeature.java
> +		if (world.getBlockState(pos.down()) != Blocks.GRASS_BLOCK.getDefaultState()) return false;
Just don't return false on the same line

2020-04-13 20:57 UTC, NeusFear approved these changes
These look good to me

2020-04-13 21:30 UTC, coderbot16 requested changes
Some minor concerns, otherwise this looks good.

2020-04-13 21:30 UTC, coderbot16 commented on src/main/java/com/terraformersmc/terrestria/init/TerrestriaGeneration.java
> +			OverworldBiomes.addHillsBiome(OUTBACK, OUTBACK, 2);
Maybe it's okay to have ulurus be super common instead of diluted

2020-04-13 21:30 UTC, coderbot16 commented on src/main/java/com/terraformersmc/terrestria/feature/trees/ShrubFeature.java
> +		//only generate on grass
`//text` -> `// text` please

2020-04-13 21:30 UTC, coderbot16 commented on src/main/java/com/terraformersmc/terrestria/feature/trees/ShrubFeature.java
> +			pos = pos.up();
```suggestion
			pos = pos.up();
			world.setBlockState(pos, config.woodState, 2);
```

2020-04-13 21:37 UTC, coderbot16 approved these changes

2020-04-13 21:37 UTC, merged

2021-12-30 06:10 UTC, valoeghese commented
Still think the original ulurus looked better ;)