Add Andisol Farmland
TerraformersMC/Terrestria pull request #116
Opened 2020-04-13 22:22 UTC by Prospector

2020-04-14 15:09 UTC, coderbot16 requested changes
Functionality looks good, some minor issues. Also, it looks like you're missing tags and loot tables.

2020-04-14 15:09 UTC, coderbot16 commented on src/main/java/com/terraformersmc/terrestria/init/TerrestriaBlocks.java
> +		BASALT_FARMLAND = TerrestriaRegistry.register("basalt_farmland", new TerraformFarmlandBlock(FabricBlockSettings.copy(Blocks.FARMLAND).materialColor(MaterialColor.BLACK).breakByTool(FabricToolTags.S
Maybe it would be better to call it andisol farmland even in the code?

2020-04-14 15:09 UTC, coderbot16 commented on src/main/java/com/terraformersmc/terrestria/init/TerrestriaBlocks.java
> +		HoeUtil.putTillable(BASALT_DIRT, BASALT_FARMLAND.getDefaultState());
Maybe in the style of fabric API this could be called TillableBlockRegistry or something like that.

2020-04-16 17:26 UTC, coderbot16 requested changes
I'd just like the volcanic rock names to be consistent with 1.16, otherwise thsi looks good.

2020-06-27 22:29 UTC, Prospector commented
Added in 1.16/v2.0.0

2020-06-27 22:29 UTC, closed without merging