Climatic World Type Compat
TerraformersMC/Terrestria pull request #90
Opened 2019-12-12 02:49 UTC by valoeghese

2019-12-12 04:08 UTC, valoeghese commented
Wow I approve of this pr

2019-12-12 04:30 UTC, coderbot16 requested changes
Overall looks alright, but there's some things that need to be fixed up.

2019-12-12 04:30 UTC, coderbot16 commented on src/main/java/com/terraformersmc/terrestria/Terrestria.java
> +	private static boolean isModLoaded(String id) {
not sure if this is necessary

2019-12-12 04:30 UTC, coderbot16 commented on src/main/java/com/terraformersmc/terrestria/compat/BiomeEnabledConfigCache.java
> +public class BiomeEnabledConfigCache {
why not just use a `HashSet<String>`?

2019-12-17 04:53 UTC, valoeghese commented
Can I merge this now

2019-12-17 05:30 UTC, merged